// Generated by brand/scripts/build.mjs from brand/mark.mjs — do not edit.
export const MARK_GRID = 48;
export const MARK_TILE = { x: 3, y: 3, size: 42, radius: 10 } as const;
export const MARK_GLYPH = {
  master: {
    d: 'M10 25.5H17L24 33.5L38 14',
    stroke: 4.5,
  },
  small: {
    d: 'M10 25.5H17L24 33L38 14.5',
    stroke: 5,
  },
  micro: {
    d: 'M9 27H18L24 33L39 15',
    stroke: 6,
  },
} as const;
export const MARK_COLOUR = { top: '#227c45', bottom: '#135c30', signal: '#b2f48c' } as const;
export const MARK_MORPH_NAME = 'vitals-mark';
export const MARK_INTRO_MS = 900;

export type MarkVariant = keyof typeof MARK_GLYPH;

/** The optical variant for a rendered pixel size; see brand/mark.mjs. */
export function markVariantFor(px: number): MarkVariant {
  if (px <= 20) return 'micro';
  if (px <= 48) return 'small';
  return 'master';
}
