<#
.SYNOPSIS
  Regenerates THIRD_PARTY_NOTICES.md: every Rust crate and npm package that
  ships inside the desktop app, with its licence.

.DESCRIPTION
  MIT and Apache-2.0 both require their notices to travel with the binary.
  Built from `cargo metadata` (normal dependencies of the desktop crate, for
  the Windows target) and `pnpm licenses list --prod` for the webview, so no
  extra tool has to be installed. `-Check` fails when the committed file is
  stale, which is how CI keeps it true after a dependency bump.
#>
param([switch]$Check)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root 'THIRD_PARTY_NOTICES.md'

Push-Location $root
try {
  $meta = cargo metadata --format-version 1 --filter-platform x86_64-pc-windows-msvc --locked | ConvertFrom-Json
  $byId = @{}
  foreach ($p in $meta.packages) { $byId[$p.id] = $p }
  $nodes = @{}
  foreach ($n in $meta.resolve.nodes) { $nodes[$n.id] = $n }

  # Walk normal (non-dev, non-build) edges from the desktop crate and the CLI.
  $roots = $meta.packages | Where-Object { $_.name -in 'vitals-desktop', 'vitals-cli' } | ForEach-Object id
  $seen = [System.Collections.Generic.HashSet[string]]::new()
  $stack = [System.Collections.Generic.Stack[string]]::new()
  foreach ($r in $roots) { $stack.Push($r) }
  while ($stack.Count -gt 0) {
    $id = $stack.Pop()
    if (-not $seen.Add($id)) { continue }
    foreach ($dep in $nodes[$id].deps) {
      $normal = @($dep.dep_kinds | Where-Object { $null -eq $_.kind }).Count -gt 0
      if ($normal) { $stack.Push($dep.pkg) }
    }
  }
  $crates = foreach ($id in $seen) {
    $p = $byId[$id]
    if ($p.source -eq $null) { continue } # workspace members are ours
    [pscustomobject]@{ Name = $p.name; Version = $p.version; License = ($p.license ?? 'see repository'); Url = ($p.repository ?? "https://crates.io/crates/$($p.name)") }
  }
  $crates = $crates | Sort-Object Name, Version

  $npmRaw = pnpm --filter @vitals/desktop licenses list --prod --json 2>$null | Out-String
  $npm = @()
  if ($npmRaw.Trim()) {
    $parsed = $npmRaw | ConvertFrom-Json
    foreach ($lic in $parsed.PSObject.Properties) {
      foreach ($pkg in $lic.Value) {
        foreach ($v in @($pkg.versions)) {
          $npm += [pscustomobject]@{ Name = $pkg.name; Version = $v; License = $lic.Name; Url = ($pkg.homepage ?? "https://www.npmjs.com/package/$($pkg.name)") }
        }
      }
    }
  }
  $npm = $npm | Where-Object { $_.Name -notlike '@vitals/*' } | Sort-Object Name, Version
} finally {
  Pop-Location
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# Third-party notices')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Vitals is MIT-licensed (see [LICENSE](LICENSE)). It is built on the open-source')
[void]$sb.AppendLine('components below, each under its own licence. Generated by')
[void]$sb.AppendLine('`scripts/third-party-notices.ps1` from the lockfiles; do not edit by hand.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('The full text of each licence is in the component''s repository, linked below.')
[void]$sb.AppendLine('The standard texts: [MIT](https://opensource.org/license/mit),')
[void]$sb.AppendLine('[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0),')
[void]$sb.AppendLine('[BSD-3-Clause](https://opensource.org/license/bsd-3-clause),')
[void]$sb.AppendLine('[ISC](https://opensource.org/license/isc-license-txt),')
[void]$sb.AppendLine('[Zlib](https://opensource.org/license/zlib),')
[void]$sb.AppendLine('[Unicode-3.0](https://www.unicode.org/license.txt),')
[void]$sb.AppendLine('[MPL-2.0](https://www.mozilla.org/en-US/MPL/2.0/).')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Microsoft Edge WebView2 is a component of Windows, installed and licensed by')
[void]$sb.AppendLine('Microsoft; Vitals does not redistribute it.')
[void]$sb.AppendLine()
foreach ($section in @(@{ Title = "Rust crates ($(@($crates).Count))"; Rows = $crates }, @{ Title = "JavaScript packages ($(@($npm).Count))"; Rows = $npm })) {
  [void]$sb.AppendLine("## $($section.Title)")
  [void]$sb.AppendLine()
  [void]$sb.AppendLine('| Component | Version | Licence |')
  [void]$sb.AppendLine('| --- | --- | --- |')
  foreach ($r in $section.Rows) {
    $lic = ($r.License -replace '\|', '\|') -replace '/', ' OR '
    [void]$sb.AppendLine("| [$($r.Name)]($($r.Url)) | $($r.Version) | $lic |")
  }
  [void]$sb.AppendLine()
}
$text = $sb.ToString().Replace("`r`n", "`n").TrimEnd() + "`n"

if ($Check) {
  $current = if (Test-Path $out) { [IO.File]::ReadAllText($out).Replace("`r`n", "`n") } else { '' }
  if ($current -ne $text) { throw 'THIRD_PARTY_NOTICES.md is stale: run scripts/third-party-notices.ps1' }
  Write-Host 'THIRD_PARTY_NOTICES.md is current'
  exit 0
}
[IO.File]::WriteAllText($out, $text, [Text.UTF8Encoding]::new($false))
Write-Host "wrote $out  ($(@($crates).Count) crates, $(@($npm).Count) npm packages)"
