//! Generates the barrel `index.ts` for the generated TypeScript.
//!
//! ts-rs emits one file per type and no index, which would force every
//! consumer to import from deep generated paths — coupling call sites to the
//! generator's file layout. This test writes the barrel as a side effect of
//! the same `cargo test` run that produces the types, so the two can never
//! disagree.
//!
//! Written as a test rather than a `build.rs` deliberately: a build script
//! runs on every compile including in a published crate, whereas binding
//! generation is a development-time concern that belongs with the export
//! tests it must run after.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const HEADER: &str = "// Generated by `cargo test -p vitals-core`. Do not edit.\n\
                      // Re-exports every type produced by ts-rs so consumers import from\n\
                      // `@vitals/protocol` rather than from generated file paths.\n";

fn generated_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("packages/protocol/src/generated")
}

#[test]
fn writes_barrel_index() {
    let root = generated_root();
    let core = root.join("core");

    if !core.is_dir() {
        // The export tests populate this directory. When the whole suite runs
        // they may not have finished yet, and on a filtered run they may not
        // have run at all; either way this is not a failure.
        eprintln!("skipping: {} not present yet", core.display());
        return;
    }

    let modules = collect_modules(&core);
    assert!(
        !modules.is_empty(),
        "no generated types found in {}",
        core.display()
    );

    let mut out = String::from(HEADER);
    for name in &modules {
        let _ = writeln!(out, "export type * from './core/{name}';");
    }

    let index = root.join("index.ts");
    // Only write on change so the file's mtime does not churn and retrigger
    // the Vite dev server on every cargo test.
    let unchanged = fs::read_to_string(&index).is_ok_and(|existing| existing == out);
    if !unchanged {
        fs::write(&index, &out).expect("writing barrel index");
    }
}

/// Module names, sorted, so the emitted file is byte-stable across runs.
///
/// A non-deterministic ordering would make the CI drift check fail at random,
/// which trains people to ignore it.
fn collect_modules(dir: &Path) -> BTreeSet<String> {
    let mut names = BTreeSet::new();

    let Ok(entries) = fs::read_dir(dir) else {
        return names;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_some_and(|e| e == "ts")
            && let Some(stem) = path.file_stem().and_then(|s| s.to_str())
            && stem != "index"
        {
            names.insert(stem.to_owned());
        }
    }

    names
}
